using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTest
{
    [TestClass]
    public class UnitTest1
    {
        // By default, unit testing assumes that exceptions are thrown when actions are invalid.
        // CTRL R, A to run
        // Alternatively, go to Tests > Run > All Tests

/*        int one, two, three;

        [TestInitialize]
        public void Initialize()
        {
            one = 1;
            two = 2;
            three = 3;
        }

        [TestMethod]
        public void TestMethod1()
        {
            Assert.IsTrue(true);
            Assert.IsFalse(false);
            Assert.IsNull(null);

            Assert.AreEqual(3, three);
            Assert.AreNotEqual("not Expected", "actual value");
        }

        [TestMethod]
        public void TestMethod2()
        {
            try
            {
                int div = 1 / (one * 2 - two);
                Assert.Fail();
            } catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

        }

    */
    }
}
